name: ficha
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.3.1"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.4
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dropdown_button2: ^2.1.0
  flutter_modular: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/Shield.svg
    - assets/spells.json
    - assets/equipaments.json
